version: "3.9"

services:
  zona-profesor:
    container_name: zona-profesor
    build: .
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=zonaprofesor.iutjmc.com.ve
      #- VIRTUAL_PORT=80
      #- LETSENCRYPT_HOST=iutjmc.com.ve
      #- LETSENCRYPT_EMAIL=admin@iutjmc.com.ve

networks:
  default:
    name: cloud_default
