version: "3.9"

services:
    zona-profesor:
        container_name: zona-profesor
        image: node:14-alpine
        volumes:
            - ./:/app:cached
            - /app/node_modules/
        working_dir: /app
        expose:
            - 80
        networks: 
            - default
        environment:
            - VIRTUAL_HOST=zonaprofesor.iutjmc.com.ve
        command: [sh,-c,"npm install && npm start"]
        tty: true


networks: 
  default:
      name: cloud_default 
