version: "3.9"

services:
    zona-profesor:
        container_name: zona-profesor
        image: node:14-alpine
        volumes:
            - ./:/app:cached
            - /app/node_modules/
        working_dir: /app
        port:
            - 3000:3000
        command: [sh,-c,"npm install && npm start"]
        tty: true


networks: 
  default:
      name: nuevo_default 
